### ISSUE TITLE
Candidate amount & layout cannot be customized

### ISSUE THREAD

**Issue by kuanyui** [fcitx/fcitx5-chewing#10]
Tested under fcitx 5.0.10

- In fcitx5 chewing, candidate amount is limited within only 5 (too less!), and the layout is horizontal which is a little hard to read.
![Screenshot_20211125_145254](https://user-images.githubusercontent.com/1370070/143393730-bc202455-4b56-4007-8752-472ec01c3ced.png)

- In contrast, fcitx5 mozc has 9 candidates in candidate popup, and layout is vertical by default.
![Screenshot_20211125_145317](https://user-images.githubusercontent.com/1370070/143393764-55423d7c-9bbd-4dc1-94b7-ddfbe44f5cb0.png)

- And both chewing & mozc in fcitx5 seems not support customizing candidate amount nor layout.

**Comment by wengxt** [comment]
It's actually possible, but not in a good place and has some issue. (global config & classicui)

**Comment by kuanyui** [comment]
It's true... Thanks a lot!
![Screenshot_20211126_120035](https://user-images.githubusercontent.com/1370070/143524999-819998ed-9933-4132-b743-3bde7bf8f130.png)
![Screenshot_20211126_120208](https://user-images.githubusercontent.com/1370070/143525002-40169c37-f3c2-4465-833a-3a6a210ab079.png)

![Screenshot_20211126_120327](https://user-images.githubusercontent.com/1370070/143525067-75db5a13-a5d6-4ed2-a44f-1eb150a2bd70.png)
