### ISSUE TITLE
word repeat issue

### ISSUE THREAD

**Issue by YSW0630** [fcitx/fcitx5-chewing#17]
When I confirm the letter,  press "Enter" (no underline) then press "Backspace", the letter I typed will repeted.
Ex: 你好 --> Press "Enter" + "Backspace" key --> 你好你好

My Environment:

Name            : fcitx5
Version         : 5.1.9-1

Name            : fcitx5-chewing
Version         : 5.1.2-1

Name            : fcitx5-qt
Version         : 5.1.6-1

Name            : fcitx5-gtk
Version         : 5.1.3-1

**Comment by wengxt** [comment]
Will look into it and make new release soon

**Comment by wengxt** [comment]
@ttobiichi3227 @YSW0630 can you help check if master has fixed this issue?

**Comment by yan12125** [comment]
I got the same issue (repeated words) with fcitx5-chewing 5.1.2-1, and I can confirm the issue is gone with fcitx5-chewing-git 5.1.2.r3.g924e4c6-1. Thank you for the fast fix!

**Comment by wengxt** [comment]
@yan12125 thanks, I'll do a new release 5.1.3 now.

**Comment by YSW0630** [comment]
@wengxt Please also update it to archlinux official repository, Thx!

**Comment by wengxt** [comment]
@YSW0630 distro package is managed by distro, not us. I pinged the packager on chat.

**Comment by felixonmars** [comment]
> @wengxt Please also update it to archlinux official repository, Thx!

The Arch package has been updated: https://gitlab.archlinux.org/archlinux/packaging/packages/fcitx5-chewing/-/commit/934a0ae7523f539036133d1ae5cba68bbc584309

**Comment by YSW0630** [comment]
Yea I see, now it works properly @wengxt thank you very much!
