### ISSUE TITLE
使用上下方向鍵選字功能

### ISSUE THREAD

**Issue by frank89722** [fcitx/fcitx5-chewing#2]
在fcitx5-rime輸入法上可實現使用上下方向鍵選字的功能，不知道在新酷音能不能增加這個功能

**Comment by wengxt** [comment]
Chewing 的按键行为都是 libchewing 控制的，看起来并没有很多可以自定义某个按键行为的办法。建议提交给 libchewing。

另外你可以试试 fcitx5-zhuyin，提供了比较多的按键自定义选项。

**Comment by wengxt** [comment]
考虑用 ibus-chewing 的方式实现一下，虽然比较 hacky
