### ISSUE TITLE
Deletion bug

### ISSUE THREAD

**Issue by WayneYam** [fcitx/fcitx5-chewing#22]
## Expected behavior

When backspace is pressed, one block character of whether the preedit or the text should be deleted

### Example

I use | to represent the cursor, and italic to represent preedit, with chewing symbol representing partially inputted characters

*小ㄕㄨㄛ*| => *小ㄕㄨ*| => *小ㄕ*|

看*小ㄕ|* => 看*小*| => 看|

## Actual behavior

The following is observed in all tested scenario

*小ㄕㄨㄛ*| => *小*| => *小*| => |
*小ㄕㄨ*| => *小*| => *小*| => |
*小ㄕ*| => *小*| => *小*| => |

Specifically on neovim v10.0 and Word online, the following is observed

看*小ㄕㄨ|* => *小*| => *小*| => |
看*小ㄕ|* => *小*| => *小*| => |

## How to reproduce

Type the above sequences

## Specifications

fcitx5 5.1.10-1
fcitx5-chewing 5.1.4-1
Kernel: 6.9.3-arch1-1
DE: Sway
Distro: Arch Linux

I'm on Arch with `sway-im` and `nvidia-beta` drivers installed.

**Comment by wengxt** [comment]
Should be fixed by 

https://github.com/fcitx/fcitx5-chewing/commit/a9c1b795de42316c4b00b7740c9ec17c453ba25a
