### ISSUE TITLE
all the word will disappear when input more than 18 chinese word

### ISSUE THREAD

**Issue by l12436** [fcitx/fcitx5-chewing#3]
**Describe the bug**
If the problem is about you can not use fcitx in certain application, or the input window is placed in wrong place, be sure to include which application is being typed, and the output of fcitx5-diagnose command.

**To Reproduce**
1. running "wine notepad"
2. 測試*20
3. than you will see the buffer all disappear after around 19 word

**Expected behavior**
it should preserve waiting word or output to application. not disappear

**Desktop (please complete the following information):**
 - Desktop: (KDE, GNOME, etc)
KDE
 - Display server type: X11, Wayland
X11
 - The output of fcitx5-diagnose if possible.
[stdout.gz](https://github.com/fcitx/fcitx5/files/5673204/stdout.gz)

**Additional context**

**Comment by l12436** [comment]
I checkout to latest master, It still disappear after 19 word !?
trying on wine notepad

**Comment by wengxt** [comment]
you need fcitx5 and fcitx5-chewing master

**Comment by l12436** [comment]
issue is solve under wine notepad, but still happened on LINE which is also running by wine....

**Comment by wengxt** [comment]
The issue is not in fcitx. I installed line and did some simple test. So here's the things happen:
when you type over 20 char, chewing will commit the first char to the applications.
In Line specifically, this commit will trigger line to send a Reset signal to input method, which will make input method to clear everything (Clear everything when receive reset signal is the right thing to do from input method point of view, but application shouldn't do that anyway.).

There is nothing I could do about that. Maybe you just live with it or use another implemenation of line (I saw they have chrome extension which should also works for linux).

**Comment by l12436** [comment]
> The issue is not in fcitx. I installed line and did some simple test. So here's the things happen:
> when you type over 20 char, chewing will commit the first char to the applications.
> In Line specifically, this commit will trigger line to send a Reset signal to input method, which will make input method to clear everything (Clear everything when receive reset signal is the right thing to do from input method point of view, but application shouldn't do that anyway.).
> 
> There is nothing I could do about that. Maybe you just live with it or use another implemenation of line (I saw they have chrome extension which should also works for linux).

I have some suggestion/idea maybe could make is happen less, 
1. add an option for commit all the word in buffer if word over 20
2. add an option when user type symbol like ，/。 etc.,  than send all the word to application.
 what do you think ?

**Comment by wengxt** [comment]
Due to the fact of how it is implemented, please submit such quest to
libchewing.

l12436 <notifications@github.com>于2020年12月11日 周五03:15写道：

**Comment by l12436** [comment]
I have found the API, seems call chewing_set_maxChiSymbolLen(), but the fact is chewing is only allow 39 byte, which is around 19 word, and buffer will overflow. 
I have manually increase to larger number, you may try to use that API to set an option.
