### ISSUE TITLE
allow output upper case English word when chewing is activate

### ISSUE THREAD

**Issue by l12436** [fcitx/fcitx5-chewing#5]
current when chewing is activated, I pressed shift try to input English, It always output lower case,
Is there any chance to add an option to allow output upper case when chewing is activated ?

**Comment by wengxt** [comment]
This should goes to libchewing. I didn't find relevant api allow me to set such option.

**Comment by l12436** [comment]
OK, I found it, is lay on libchewing chewingio.c:1577, which is forcing english to be lower case.
I just remove that and it working.
