### ISSUE TITLE
License alignment with fcitx5

### ISSUE THREAD

**Issue by tyb-dev** [fcitx/fcitx5-chewing#8]
Hello!

fcitx-chewing is distributed under the GPL while the fcitx5 itself is LGPL. Would it be possible to distribute this plugin under the same license as fcitx5? Thanks!

**Comment by wengxt** [comment]
I don't think it really matters. When people distribute them, they are distributed as individual packages. End user can use it anyway in any sense, GPL is not applied to end users.

Only when some one distribute them as a whole software, they need to be considered to be released under GPL. But in that case, the consequences is that you need to have all fcitx5, fcitx5-chewing source code available, and that's not an issue for linux distributions.

As long as fcitx5 is released under a gpl-compatible licenese ( means it can be re-released under GPL), it should be fine.

I'll consider your request anyway, but we need confirmation from other contributors.
